apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
type: Opaque
data:
  # postgresql://postgres:pass123@postgres-svc:5432/mydb?schema=public
  DATABASE_URL: cG9zdGdyZXNxbDovL3Bvc3RncmVzOnBhc3MxMjNAcG9zdGdyZXMtc3ZjOjU0MzIvbXlkYj9zY2hlbWE9cHVibGlj
